Fix flakey test that fails because of geocoder stub behaviour
The test was failing with
NoMethodError: undefined method `[]' for nil:NilClass
When calling `Geocoder.coordinates` vs ActiveRecord geocoder
behaviour, the stub behaves differently. The ActiveRecord version
does not expect nil, while the normal one does. Change stubs to
always return an empty array instead of nil to avoid any unsuspected
behaviour. We will not lose any validation as we are calling `.present?`
on the response which will return false both ways